### ISSUE TITLE
Icon Corruption

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#87] opened 2015-06-04 05:54 UTC
One of the CM icons got corrupted in a recent update.

![2015-06-03_21-53-03](https://cloud.githubusercontent.com/assets/1563559/7977802/069b992a-0a3b-11e5-9cd0-ac2ed23d92e1.png)

**Comment by Reedyseth** [comment] 2015-12-21 23:37
I would like to reopen this issue since in the latest update of Comment Mail Pro I see a wrong Icon on the CM panels, at least this is my perception.

![image](https://cloud.githubusercontent.com/assets/1228711/11944074/32774e0a-a800-11e5-982a-d3ac9cea8629.png)


As you can see on the image there is a broom instead of the CM envelop Icon, perhaps there is a conversation that I missed regarding this matter, can you confirm the issue.

Using the version https://github.com/websharks/comment-mail-pro/commit/139012a50e8c9d476dd3d76195948114e6740757

**Comment by raamdev** [comment] 2015-12-22 17:04
@Reedyseth Thank you for the report. I've actually seen that too (namely in the icon that shows up in each subscriber row) and I thought it was just a browser caching glitch. That may still be what it is (possibly related to our testing various versions of the plugin), but we should investigate more closely to make sure this isn't a bug.

**Comment by raamdev** [comment] 2015-12-22 17:05
The broom icon is used by ZenCache and should not appear in Comment Mail.

**Comment by Reedyseth** [comment] 2015-12-22 17:10
Thank you for taking a look at the report !

**Comment by Reedyseth** [comment] 2015-12-22 18:20
I just digg a bit and found that the Icon assigment by Comment Mail is correct, this is using the code on the CSS Style:
```css
content: '\e000'
```
Also ZenCache uses the same reference to the Icon, so having both plugins installed is causing that ZenCache overwrites the Comment Mail icon.

Changing the reference to the Icon seems to fix the issue, but I think this will break the plugin standars

```css
content: '\e001'
```
If there is not issue with this I could do more tests and then submit my pull request.

**Comment by raamdev** [comment] 2015-12-22 18:58
@Reedyseth Nice catch!! Yes, I've confirmed that is the bug here: If you install the latest version of ZenCache Pro + Comment Mail Pro, the icon that shows up in Comment Mail is incorrect (the broom).

It looks like the problem is that the Comment Mail v151221-RC is using an older version of the [Sharkicons](https://github.com/websharks/sharkicons) package.

**Comment by raamdev** [comment] 2015-12-23 03:24
@Reedyseth This has been fixed in https://github.com/websharks/comment-mail/pull/188 and https://github.com/websharks/comment-mail-pro/issues/42.

**Closed by raamdev** 2015-12-23 03:24 UTC
Labels: bug

**Comment by raamdev** [comment] 2015-12-23 03:27
Next Lite Release Changelog:

- **Bug Fix**: Fixed a bug where certain icons would not appear, or the wrong icon would appear, when Comment Mail was installed alongside the ZenCache plugin. Both plugins use the same Sharkicons library, but were using different versions, which introduced a conflict. Comment Mail has been updated to use the latest version of the Sharkicons library. Props @Reedyseth. See [Issue #87](https://github.com/websharks/comment-mail/issues/87#issuecomment-166458711).

**Comment by raamdev** [comment] 2015-12-23 03:27
Next Pro Release Changelog:

- **Bug Fix**: Fixed a bug where certain icons would not appear, or the wrong icon would appear, when Comment Mail was installed alongside the ZenCache plugin. Both plugins use the same Sharkicons library, but were using different versions, which introduced a conflict. Comment Mail has been updated to use the latest version of the Sharkicons library. Props @Reedyseth. See [Issue #87](https://github.com/websharks/comment-mail/issues/87#issuecomment-166458711).

**Comment by raamdev** [comment] 2015-12-24 23:10
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#87).

**Comment by Reedyseth** [comment] 2015-12-27 01:39
> This has been fixed in #188 and websharks/comment-mail-pro#42.

Awesome, you spot the issue very fast, thank you for the update :)
