### ISSUE TITLE
Bug: Plugin Links Overlapping

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#236] opened 2016-02-15 06:26 UTC
## Overview

The plugin-related links overlap other portions of the menu page whenever the logo is not shown.

## Steps to Reproduce

- Activate Comment Mail Pro.
- Visit Config. Options page.
- Turn off the logo display in administrative areas. It's the default setting in the pro version.

![2016-02-14_21-23-51](https://cloud.githubusercontent.com/assets/1563559/13041194/76c30b12-d361-11e5-86f2-85eb10f2b69f.png)

---

![2016-02-14_21-23-24](https://cloud.githubusercontent.com/assets/1563559/13041195/76c69af2-d361-11e5-8957-070bbdf2d16d.png)

**Comment by raamdev** [comment] 2016-02-19 02:17
Yep, I was able to reproduce this too.

**Comment by raamdev** [comment] 2016-02-19 02:17
@renzms Could you look into this?

**Comment by renzms** [comment] 2016-02-19 02:20
> Could you look into this?

@raamdev Sure!

**Comment by renzms** [comment] 2016-03-04 16:57
@raamdev @jaswsinc 

Changed the following in the CSS, before committing though I'd just like to share the screens.

Without the logo, did you want the options on the Left near the dividing line or more aligned to the top just like the options on the right?

```
menu-page .pmp-heading {
 padding-bottom: 3em;
 margin-bottom: 2em;
 position: relative;
 min-height: 80px;
}

.pmp-heading-links {
 float: left;
 clear: left;
}
```
![screen shot 2016-03-05 at 12 54 21 am](https://cloud.githubusercontent.com/assets/13220018/13533769/e7a86434-e26c-11e5-8e77-80f2188a6b97.png)

![screen shot 2016-03-05 at 12 54 32 am](https://cloud.githubusercontent.com/assets/13220018/13533770/e933edfa-e26c-11e5-915d-9a6dd3ce6636.png)

**Comment by raamdev** [comment] 2016-03-04 17:46
Hmm, I'm not sure why the Logo is missing in the Lite version... it should always show up there IMO.

**Comment by raamdev** [comment] 2016-03-04 17:47
Also, it looks like those options get pushed down when a Dashboard notice (such as the "Upgrading from StCR" notice) appears:

![2016-03-04_12-44-11](https://cloud.githubusercontent.com/assets/53005/13535223/279202c8-e207-11e5-944b-1c40c44f39e0.png)

We need to make sure that gets fixed as part of this GitHub issue too.

**Comment by renzms** [comment] 2016-03-05 10:23
@raamdev 
> Hmm, I'm not sure why the Logo is missing in the Lite version... it should always show up there IMO.

The screenshots I provided is the observed behaviour when the logo display is turned off/on in the administrative area when using Pro. 




> Also, it looks like those options get pushed down when a Dashboard notice (such as the "Upgrading from StCR" notice) appears:

This I have not tested yet, but maybe the changes I made to the CSS will stop even the notices from pushing it too far down the break line.

**Comment by raamdev** [comment] 2016-03-05 14:26
> maybe the changes I made to the CSS will stop even the notices from pushing it too far down the break line.

Can you test that?

> The screenshots I provided is the observed behaviour when the logo display is turned off/on in the administrative area when using Pro.

Oh, I see. I did not even realize that was an option. Ha! The way you have the options in those screenshots looks perfect to me.

**Comment by renzms** [comment] 2016-03-05 15:09
@raamdev 
> Can you test that?

I rolled back to ZenCache and updated some options to get some notifications up, then added my css changes:

![screen shot 2016-03-05 at 11 07 26 pm](https://cloud.githubusercontent.com/assets/13220018/13548271/20add272-e327-11e5-8b4a-8cc9012c3fbb.png)

**Comment by raamdev** [comment] 2016-03-05 15:15
What about installing StCR, adding a subscription, then installing Comment Mail so that the Upgrading from StCR message shows up? That's the more likely message for Comment Mail users to see, so I just want to make sure it works with that.

**Comment by raamdev** [comment] 2016-03-05 15:16
Also, can you please submit a PR for this with whatever code you're testing these screenshots with?

**Comment by renzms** [comment] 2016-03-05 15:23
> What about installing StCR, adding a subscription, then installing Comment Mail so that the Upgrading from StCR message shows up? That's the more likely message for Comment Mail users to see, so I just want to make sure it works with that.

Sure, tested and still works like a charm. I'll submit a PR as well.
Here you go:

![screen shot 2016-03-05 at 11 22 08 pm](https://cloud.githubusercontent.com/assets/13220018/13548359/389d99ec-e329-11e5-8a46-59cbe6d59b21.png)

**Comment by raamdev** [comment] 2016-03-16 16:18
Fixed via https://github.com/websharks/comment-mail-pro/issues/61.

**Closed by raamdev** 2016-03-16 16:18 UTC
Labels: bug, high priority, ready for work, user interface
