### ISSUE TITLE
CSS Styling Error on Login Page

### ISSUE THREAD

**Issue by kristineds** [websharks/comment-mail#109] opened 2015-06-25 16:01 UTC
Using current version (as of v150625), when Comment Mail is installed, activated, and then enabled, it is displaying css styling errors on the WP Login Page 

![screen shot 2015-06-25 at 11 04 21 pm](https://cloud.githubusercontent.com/assets/7514953/8358996/28f219e2-1b96-11e5-9925-6dd905f0bfa4.png)

**Comment by raamdev** [comment] 2015-06-26 01:52
@kristineds I'm not able to reproduce this bug by following the steps that you provided. Could you try reproducing this on a clean WordPress installation and provide me with a list of steps?

**Comment by raamdev** [comment] 2015-06-26 02:11
I was able to reproduce this bug after enabling SSO and following the steps to enable Google SSO: http://comment-mail.com/kb-article/sso-integration/#-google

**Comment by kristineds** [comment] 2015-06-26 02:15
@raamdev : That could be it. That's the only thing I did on the clean WP installation (demo site). 
Another bug related to Google SSO integration that _might_ be related this. #110

**Comment by jaswsinc** [comment] 2015-06-26 05:05
Reproduced also. Thanks! ~ Taking a look.

**Comment by jaswsinc** [comment] 2015-06-26 05:07
Noting that this bug exists in the Simple (i.e., `type-s`) template set only.

**Comment by jaswsinc** [comment] 2015-06-26 05:19
Fixed in dev branch.

**Closed by jaswsinc** 2015-06-26 05:19 UTC
Labels: bug

**Comment by jaswsinc** [comment] 2015-06-26 07:38
@kristineds Thanks for reporting this! :-)

**Comment by kristineds** [comment] 2015-06-26 08:56
> Thanks for reporting this! :-)

Glad to help. :)
