### ISSUE TITLE
Fatal Error When Opening Page for Editing

### ISSUE THREAD

**Issue by patdumond** [websharks/comment-mail#138] opened 2015-08-08 23:16 UTC
I installed Comment-Mail on a new website. I went in to edit the sole page on the site and found the following error message:

```
Error Message

Fatal Error: Uncaught exception 'Exception' with message 'Query failure.' in /home/pdphoto/public_html/wp-content/plugins/comment-mail/includes/classes/utils-sub.php:627 Stack trace: #0 /home/pdphoto/public_html/wp-content/plugins/comment-mail/includes/classes/post-small-meta-box.php(56): comment_mail\utils_sub->query_total('9') #1 /home/pdphoto/public_html/wp-content/plugins/comment-mail/includes/classes/post-small-meta-box.php(43): comment_mail\post_small_meta_box->display() #2 /home/pdphoto/public_html/wp-content/plugins/comment-mail/plugin.inc.php(1174): comment_mail\post_small_meta_box->__construct(Object(WP_Post)) #3 [internal function]: comment_mail\plugin->post_small_meta_box(Object(WP_Post), Array) #4 /home/pdphoto/public_html/wp-admin/includes/template.php(1074): call_user_func(Array, Object(WP_Post), Array) #5 /home/pdphoto/public_html/wp-admin/edit-form-advanced.php(607): do_meta_boxes('page', 'side', Object(WP_Post)) #6 /home/pdphoto/public_html/wp-admin/post.php(213): include('/home/pdphoto/p...') #7 {main} in /home/pdphoto/public_html/wp-content/plugins/comment-mail/includes/classes/utils-sub.php on line 627
Description

The Comment Mail plugin code created an error that caused PHP execution to fail.
```

I thought it might have been a problem with the theme (iThemes Builder) so I activated 2015. Still got the error when I went in to edit the page. The error message does not appear when add a new page or post, but neither does the "Comment-Mail" metabox.  I don't remember what Comment-Mail settings I had on the page, sorry.

Site is at WordPress 4.2.4.

**Comment by jaswsinc** [comment] 2015-08-14 12:54
@patdumond Thanks for the report!

Can you confirm that you do have the DB table `wp_comment_mail_subs`? If you inspect your WordPress database with a tool like PhpMyAdmin, do you have this table?

**Comment by patdumond** [comment] 2015-08-14 13:03
I'll check it out. I have to admit I uninstalled CommentMail. This is the only site (out of 3-4 that I've installed it on) that I've seen this issue and it except for the theme and iThemes Security it was pretty much still a clean install. I'll see if I can reproduce the problem and check for that table.

**Comment by jaswsinc** [comment] 2015-08-14 13:05
Thank you. No worries. If you can that's great. If not, we can go with what you provided already.

**Comment by patdumond** [comment] 2015-08-14 14:42
When I reinstalled the problem was gone. Comment Mail looks fine. Haven't tested whether it actually works, but it is enabled and everything  on the back end is fine. I even switched back to the Visual Composer theme I had installed the other day and reinstalled and activated Visual Composer. Whatever glitch it was, isn't there anymore. I'm going to close this issue.

**Comment by jaswsinc** [comment] 2015-08-19 05:03
> Whatever glitch it was, isn't there anymore. I'm going to close this issue.

Copy that. Thanks for testing!

I'm going to reopen this just in case it surfaces again. The fact that you saw this exception is a bit concerning. It tells me there is a specific sequence of events that can lead to this problem.

**Comment by jaswsinc** [comment] 2015-09-18 20:24
Another report of this issue. Referencing internal ticket: https://websharks.zendesk.com/agent/tickets/8422

**Comment by jaswsinc** [comment] 2015-09-22 18:25
The error being `Uncaught exception 'Exception' with message 'Query failure.'` in /home/pdphoto/public_html/wp-content/plugins/comment-mail/includes/classes/utils-sub.php:627.

Referencing: https://github.com/websharks/comment-mail/blob/000000-dev/comment-mail/includes/classes/utils-sub.php#L626-L627

**Comment by raamdev** [comment] 2015-09-22 19:34
Adding this to the `Next Release` milestone, as this seems important given there have been multiple reports of this.

**Comment by jaswsinc** [comment] 2015-10-27 11:53
## Overview

We don't yet know what is causing this bug. However, there is a simple step that we can take to try and get a better Exception with details that might help us determine what is happening.

## Next Actions (Pro Version)

- New feature branch in the `websharks/comment-mail-pro` repo.

- Replace [this line](https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/classes/utils-sub.php#L627) with the following:

  ```php
  throw new \exception(sprintf(__('Query failure on SQL: `%1$s`', $this->plugin->text_domain), $sql));
  ```

- Submit PR.

## Next Actions (Lite Version)

- New feature branch in the `websharks/comment-mail` repo.

- Repeat the same step from above.

- Submit PR.

## Bonus Points

This exception is almost certainly being triggered by a malformed SQL query that is built under certain conditions. If you would like to carefully review [these lines of code](https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/classes/utils-sub.php#L597-L624) and see if you can figure out where the invalid SQL query is being generated by that code, then you can kill the bug right here and now. I took a quick look and couldn't find it.

If you can't find it either, no worries. The change in this issue should help us locate it whenever this happens (and is reported) again in the future.

**Comment by jaswsinc** [comment] 2015-10-28 02:07
@renzms While you're working on this, please change the call to `esc_html()` in [this line of code](https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/classes/utils-sub.php#L598). It should be `esc_sql` instead of `esc_html`. That's not the bug causing this problem, but it _is_ a bug nonetheless. To learn more, see: https://codex.wordpress.org/Function_Reference/esc_sql

**Comment by raamdev** [comment] 2015-10-28 04:58
I attempted to reproduce this bug by setting up a completely fresh installation of WordPress, installing Comment Mail Lite (from `000000-dev`) and then editing the sole "Hello World" post. I also tried installing Comment Mail Lite v150709 (from WordPress.org) on the same clean installation and repeating the same steps. I was not able to reproduce the Fatal Error Pat describes in this GitHub issue.

**Comment by jaswsinc** [comment] 2015-10-28 09:45
@renzms While you're working on this, please change [this line](https://github.com/websharks/comment-mail/blob/150709/comment-mail/includes/classes/utils-sub.php#L597) also.

Change:

```php
$sql = "SELECT SQL_CALC_FOUND_ROWS `ID`".
```

To:

```php
$sql = "SELECT SQL_CALC_FOUND_ROWS `email`".
```

We need to select the `email` so that when/if `$group_by_email` is enabled in this method, there is something to `GROUP BY`. The `ID` is wrong, it should be `email`.

---

Still, I searched the codebase for calls to this method that set `$group_by_email` to a `true` value and could not find one. The default value for that flag is `false`. So I don't think that's the bug causing this problem either. However, it is a bug that should be fixed.

**Comment by patdumond** [comment] 2015-10-28 12:49
@raamdev wrote: I was not able to reproduce the Fatal Error Pat describes in this GitHub issue.

I have never been able to reproduce it either although I've installed (various versions) of Comment Mail on several sites. After I reinstalled Comment Mail on the site that had the original problem I've never seen it again. The only difference between that site and the other sites I've installed it on was that when I installed Comment Mail on that site it was running a theme with Visual Composer. However, as I said I did test Comment Mail again with that VC theme after I reinstalled Comment Mail and it was working fine.

**Comment by jaswsinc** [comment] 2015-11-09 14:02
@renzms I just wanted to let you know that the work I outlined [here](https://github.com/websharks/comment-mail/issues/138#issuecomment-151467507) as it pertains to this issue is still relevant; i.e., even though we discussed some other things here, that change is still needed to help us debug this.

**Comment by renzms** [comment] 2015-11-10 01:09
@jaswsinc Made the changes from the original outline as well as the additional changes you mentioned in the next set of instructions.

I was unable to reproduce the Bug originally mentioned by Pat, should I find a way another way to test the changes?

**Comment by jaswsinc** [comment] 2015-11-10 05:22
Next Release Changelog:

- **Exception Handling:** This release improves the exception handling in a specific routine that has been reported to cause some trouble at certain times. Still a mystery at this point, but we hope that this new release with improved exception handling will help us finally track down this elusive bug. Props @renzms @patdumond. See: [this GitHub issue](https://github.com/websharks/comment-mail/issues/138) for further details.

**Comment by jaswsinc** [comment] 2015-11-10 05:22
@renzms Perfect! Thanks for those PRs. Both merged :-) :100:

**Closed by jaswsinc** 2015-11-10 05:22 UTC
Labels: bug, needs testing
