### ISSUE TITLE
Feature Request: Extend the Manage my Subscriptions feature

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail#307] opened 2016-11-01 13:22 UTC
It would be nice to extend the features of the `manage my subscriptions` link and shows the subscriptions for the logged in user.

![screen shot 2016-10-29 at 8 48 33 pm](https://cloud.githubusercontent.com/assets/13220018/19890817/e828fdbe-a077-11e6-9a56-496169b7829c.png)

Some customizable options such as the following:

- The ability to customize the url path to the subscriptions page such as `domain.com/my-subscriptions`  

- Or even the ability to show the list of subscriptions of the visitor on a page within the site's theme via a shortcode or customizable template

- If the visitor does not have a subscription to any comment, present the user on this page an option to subscribe to available pages/posts and collect their email instead of showing the error prompt:

```
Missing subscription key; unable to display summary.

```

----

Referencing internal ticket: https://websharks.zendesk.com/agent/tickets/14763

**Comment by raamdev** [comment] 2016-11-01 17:32
@renzms writes...
> If the visitor does not have a subscription to any comment, present the user on this page an option to subscribe to available pages/posts and collect their email instead of showing the error prompt: `Missing subscription key; unable to display summary.`

Can you provide me with a list of steps to reproduce this behavior?

**Comment by renzms** [comment] 2016-11-02 03:01
> Can you provide me with a list of steps to reproduce this behavior?

Sure, it doesn't happen on a normal workflow but in this case the admin user wanted a direct link available via menu to the subscriptions page.

- The `manage my subscription` link goes to this path: `domain.com/?comment_mail%5Bmanage%5D%5Bsummary%5D=k`, when visiting this link while not logged-in or either without a subscriptions it displays `Missing subscription key; unable to display summary.`

**Comment by raamdev** [comment] 2016-11-03 16:36
> when visiting this link while not logged-in

Does that link appear anywhere when not logged-in? It shouldn't, unless you've previously subscribed to a comment, which sets a cookie in your browser that then makes the link appear. So if the 'manage my subscriptions' link ever appears on the comment form of a site, the user should be able to click it and view their subscriptions. It should never appear unless you actually have a subscription.

**Comment by renzms** [comment] 2016-11-05 02:13
> It should never appear unless you actually have a subscription.

Right, customer wanted to link to a subscriptions page regardless if their visitors had previous comments and were not logged-in visitors. So they tried to use the link to go directly to the page and try to collect subscriptions without commenting in that way.

**Comment by raamdev** [comment] 2016-11-07 00:00
@renzms Right, that's the expected behavior. If the user does not have any subscriptions, we don't have anything to show them, so a link to their list of non-existent subscriptions is not shown. I don't understand why you'd want to show them the My Subscriptions page if there's nothing to show them in the first place, hence my confusion about this feature request...

**Comment by renzms** [comment] 2016-11-08 06:33
> I don't understand why you'd want to show them the My Subscriptions page if there's nothing to show them in the first place, hence my confusion about this feature request...

@raamdev 

In the original email the customer wrote in to request a direct page or link to the My Subscriptions Page, (_the main request to extend the features of my subscription page_) so any visitor could go to their "Subscriptions". If in the case, they didn't have any subscriptions, then the additional request was to allow them to view possible posts to subscribe to and collect their email without being logged in.

We can omit this part of the request then, as this is just an observed behavior by the customer when trying to link directly to the **My Subscriptions** page: 

>If the visitor does not have a subscription to any comment, present the user on this page an option to subscribe to available pages/posts and collect their email instead of showing the error prompt:

>Missing subscription key; unable to display summary.

If the feature request is just to extend the capabilities of the My Subscriptions page to a shortcode or template then they would not encounter the above error for what they are trying to attempt, which is collect emails and directly link to the Subscriptions page.

**Comment by raamdev** [comment] 2016-11-09 01:02
> If in the case, they didn't have any subscriptions, then the additional request was to allow them to view possible posts to subscribe to and collect their email without being logged in.

So, an Add Subscription page would be shown if they did not have any subscriptions? We toyed with that idea awhile back and decided against it, due to UX concerns. (How would someone know what post they want to subscribe to by selecting it from a drop-down box? They'd most likely visit the post first, _then_ subscribe, in which case the existing "Subscribe without Commenting" link should work fine.)

> extend the capabilities of the My Subscriptions page to a shortcode

I like the idea of a shortcode that could be inserted on a page to list a users subscriptions, that way a site owner could create such a page on their site using their site theme and make it look like it's part of their site (as opposed to having a custom Comment Mail-specific page for showing the subscriptions). If you could open a separate GitHub issue for that, that would be great ("Feature Request: Shortcode for My Subscriptions")

**Comment by renzms** [comment] 2016-11-09 15:37
@raamdev 

> They'd most likely visit the post first, then subscribe, in which case the existing "Subscribe without Commenting" link should work fine.)

Agreed, this would probably work better in most cases.


> If you could open a separate GitHub issue for that, that would be great ("Feature Request: Shortcode for My Subscriptions")

Cool, created new issue for that request. See: [Feature Request: Shortcode for My Subscriptions](https://github.com/websharks/comment-mail/issues/309)

**Comment by raamdev** [comment] 2016-11-09 15:43
Cool, thanks. I'll go ahead and close this issue then in favor of the one you opened.

**Closed by raamdev** 2016-11-09 15:43 UTC
Labels: enhancement, needs feedback
