### ISSUE TITLE
How to change the CSS for the Add New Subscription Page?

### ISSUE THREAD

**Issue by KTS915** [websharks/comment-mail#164] opened 2015-11-26 20:23 UTC
I have been playing with the (Pro) plugin, but cannot find a way to change the CSS for the Add New Subscription Page, except for the Header and Footer. I really need to change both the fonts and color scheme.

I have also found files with numerous calls out to Google, MaxCDN, and Cloudflare -- obviously to set the fonts and such -- none of which I want. How can I turn them all off, please?

**Comment by KTS915** [comment] 2015-11-26 20:30
The same questions apply for the My Comment Subscriptions page.

**Comment by jaswsinc** [comment] 2015-11-26 20:49
@KTS915 Try changing your template mode to "Advanced". See attached screenshot. That should give you full access to everything that is used in all of the raw template files.

![2015-11-26_11-47-34](https://cloud.githubusercontent.com/assets/1563559/11430476/9b33c81e-9433-11e5-9d16-094d38831c0c.png)

**Comment by KTS915** [comment] 2015-11-26 21:14
Aha! All is revealed! I hadn't even noticed that option! Thank you!

But now I see that I have two new issues. One is that Comment Mail is offering to let me subscribe to pages, even though I have comments on pages turned off. The second is that I don't understand the Comment box. It seems that this should be set as a numeral, but to what does the number correspond?

**Comment by KTS915** [comment] 2015-11-26 21:30
Now I see that this Comment box is offering me numbers only on posts and pages that have no comments. Obviously, it shouldn't be possible to comment on pages at all if comments are turned off, but it would also be good if this box didn't offer any options other than All Comments/Replies if the post has not so far received any comments.

**Comment by raamdev** [comment] 2015-12-13 02:17
@KTS915 writes...
> But now I see that I have two new issues. One is that Comment Mail is offering to let me subscribe to pages, even though I have comments on pages turned off. The second is that I don't understand the Comment box. It seems that this should be set as a numeral, but to what does the number correspond?
> Now I see that this Comment box is offering me numbers only on posts and pages that have no comments. Obviously, it shouldn't be possible to comment on pages at all if comments are turned off, but it would also be good if this box didn't offer any options other than All Comments/Replies if the post has not so far received any comments.

I just tested the latest dev branch of Comment Mail and I was unable to reproduce any of the behavior you're describing. When comments are disabled, the Comment Mail form does not appear. Also the latest dev branch has a new option to specify the Post Types that CM should be active on; by default it's only active on `post` Post Types and if you want to see enable Comment Mail on Pages, you need to add the `page` Post Type to the list:

![2015-12-12_21-14-19](https://cloud.githubusercontent.com/assets/53005/11764985/5c12a5c6-a115-11e5-9f00-7ba56921bece.png)

---

I'm going to close this GitHub issue for now, but once the next version of Comment Mail is released (within the next few days), please let me know if you're still having issues and I'll reopen this for further investigation. :-)

**Closed by raamdev** 2015-12-13 02:17 UTC
Labels: bug, needs testing
