### ISSUE TITLE
SSO — Without Logging In?

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comment-mail#88] opened 2015-06-05 17:07 UTC
Referencing: http://comment-mail.com/kb-article/sso-integration/

@raamdev writes...
> @jaswsinc Wow, awesome work here on this KB Article! I love all the integration steps for each provider.
> 
> One question on this:
> 
> In order for SSO to work (i.e. for SSO links to appear in your comment/login forms); your WP Discussion Settings should "require users to be logged-in" before posting a comment. Otherwise, there is no reason to log in to begin with, as you don't require user registration at all. If that's the case, we suggest NOT integrating SSO w/ Comment Mail™. It would not serve any useful purpose in such a scenario.
> 
> What if I want to leave "require users to be logged-in" disabled, so that anyone can post a comment by filling in their details in the comment form, but I also want to provide my readers with the convenience of being able to login via SSO (so that they don't have to fill in their details each time)? You say above that doing so wouldn't serve any useful purpose, but I see a very useful purpose: convenience (which is the whole point of SSO, right?)
> 
> Is there any way to have both (SSO enabled, with links appearing in the comment form + the ability for someone to just anonymously post a comment by filling in the comment form themselves)?

**Comment by jaswsinc** [comment] 2015-06-05 17:15
@raamdev Great point.

I don't see any reason we couldn't enable this for those who would prefer it this way. The only problems that I see are as follows:

- An SSO login is also going to create an account on the site for that user. That may not be desirable in some cases, and could be a side-effect that would annoy site owners who enable it without knowing this. We just need to be sure they know before doing so.

- Logging into the site this way (via a social network account) may give the user access to something they should not see on a particular site. The fact that an SSO login actually creates an account for them, allows them to log in by leaving a comment. That's something that would normally not occur on a blog where people are not required to log in. Anyway, it's just something to think about in terms of security. I will give this some more though.

---

If I understand you correctly, it would probably be more ideal (in this particular use case) for an SSO login to simply fill the fields needed in that instance of a comment form; i.e., not actually log them in. If that's the case, it may require some refactoring to consider that scenario. I see that being more challenging in terms of what is needed to make this work.

**Comment by raamdev** [comment] 2015-06-05 17:21
> If I understand you correctly, it would probably be more ideal (in this particular use case) for an SSO login to simply fill the fields needed in that instance of a comment form; i.e., not actually log them in. If that's the case, it may require some refactoring to consider that scenario. I see that being more challenging in terms of what is needed to make this work.

I don't think that's necessary. In fact, I (personally) would rather it create an account for them on my site, that way when they come back to my site to leave another comment, it looks like they're "already logged in", as opposed to just filling in the comment form fields.

> Logging into the site this way (via a social network account) may give the user access to something they should not see on a particular site.

Good point. I think we can alleviate any confusion by simply detecting if someone has not enabled "Require users to be logged in" and then showing a special additional message in the SSO Integration section that warns site owners of the potential issues related to this, something that makes it clear they understand what using that feature does (i.e., allow people to login to their WordPress site as users with the Subscriber role).

**Comment by jaswsinc** [comment] 2015-06-05 18:16
Good, good. That's easy enough. Thank you.

**Comment by raamdev** [comment] 2015-06-26 02:21
I just wanted to leave some feedback here regarding the importance of resolving the issue outlined in this GitHub Issue:

While attempting to reproduce a bug that Kristine reported (https://github.com/websharks/comment-mail/issues/110) I was following the steps outlined in the [SSO Integration](http://comment-mail.com/kb-article/sso-integration/#-google) KB Article for configuring Google SSO and after finishing all of the steps I started looking around for _how to actually login via Google SSO_... I checked the Comment Form... nothing. Then I tried the main WordPress Login Page... still nothing. I was confused and thought maybe I missed a step or forgot to do something... 

Then I decided to review the top of the SSO Integration KB Article to see if I missed any important steps and sure enough I found the [Prerequisites (Basic WP Settings)](http://comment-mail.com/kb-article/sso-integration/#toc-b0dc0397) section telling me that I needed to "require users to be logged-in", which made no sense to me (intuitively)... and that reminded me of this GitHub issue.

The reason this isn't intuitive is that other plugins that provide SSO Integration for WordPress comments (think Disqus) _do not require_ any such special WordPress Discussion configuration that requires users to be logged in to comment. (Granted, Disqus SSO doesn't create a WordPress account on the site, but that's beyond the point--it's just not expected.)

So, this is all to say that we definitely need to resolve this issue as we discussed above.

**Comment by jaswsinc** [comment] 2015-06-26 09:54
Copy that. Thanks for those thoughts @raamdev.

**Comment by jaswsinc** [comment] 2015-06-26 09:54
Noting that many themes do not display the default login link whenever comment registration is not required, and that this may require that we use a different hook if Comment Mail SSO options are to presented even with registration is not required.

**Comment by jaswsinc** [comment] 2015-06-26 11:11
Prerequisities removed from this article:
http://comment-mail.com/kb-article/sso-integration/

**Closed** 2015-06-26 11:12 UTC
Labels: enhancement

**Comment by jaswsinc** [comment] 2015-06-26 11:13
Two hooks. `comment_form_top` as a fallback.

```php
add_action('comment_form_must_log_in_after', array($this, 'comment_form_must_log_in_after'), 5, 0);
add_action('comment_form_top', array($this, 'comment_form_must_log_in_after'), 5, 0); // Secondary fallback.
```
