### ISSUE TITLE
Detect when Jetpack Subscriptions module is active and show Dashboard warning

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#113] opened 2015-06-26 02:06 UTC
The Jetpack Subscriptions module provides similar features as Comment Mail and, just as we do with StCR (see https://github.com/websharks/comment-mail/issues/97) we should detect when that Jetpack module is active and Comment Mail is enabled and show an appropriate warning message.

![2015-06-25_22-03-47](https://cloud.githubusercontent.com/assets/53005/8369357/5dea5bd8-1b86-11e5-9dbf-16dfcdf1e8ab.png)

**Comment by jaswsinc** [comment] 2015-06-26 06:20
Referencing: https://wordpress.org/support/topic/plugin-subscribe-to-comments-alignment-of-the-check-box

**Comment by jaswsinc** [comment] 2015-06-26 06:20
Referencing: https://github.com/Automattic/jetpack/search?utf8=%E2%9C%93&q=stb_enabled

**Comment by jaswsinc** [comment] 2015-06-26 06:21
Referencing: https://github.com/Automattic/jetpack/search?utf8=%E2%9C%93&q=stc_enabled&type=Code

**Comment by jaswsinc** [comment] 2015-06-26 06:43
All set in the dev branch.

**Comment by raamdev** [comment] 2015-06-26 15:03
@jaswsinc I just realized that the Jetpack Subscriptions modules does more than allow subscribing to comments: it also allows subscribing to future posts.

So what if a site owner wants to use the Jetpack Subscriptions module for allowing subscriptions to the Post but wants to use Comment Mail for comment subscriptions? I don't see any inherent problem with doing this, except that now Comment Mail is going to scream whenever the Subscriptions module is active.

What if we instead simply check if the 'follow comments' option of the Jetpack Subscriptions module is enabled and _then_ show the warning message (which will need to be updated after making this change to mention specifically the 'follow comments' option as what's causing the message to show)?

![2015-06-26_10-59-34](https://cloud.githubusercontent.com/assets/53005/8380247/b3898200-1bf2-11e5-9a1c-04c9c9ef1d3f.png)

In fact, this might be good ground for a KB Article that describes and shows a screenshot of exactly _what_ needs to be disabled, so if you agree with making this change I think the Jetpack Subscriptions module Dashboard message should be updated to link to a KB Article called "Can I use Jetpack Subscriptions with Comment Mail?"

**Comment by jaswsinc** [comment] 2015-06-26 15:24
Ah, I see what you mean. Yep, that sounds like a good idea to me! :-)

---

Might be worth opening a feature request for this too. That would make a great addition to Comment Mail, I think. That's the perfect time to pick up a new subscriber, so for us to make that possible with CM would be great.

**Comment by raamdev** [comment] 2015-06-26 15:30
> Might be worth opening a feature request for this too. That would make a great addition to Comment Mail, I think. That's the perfect time to pick up a new subscriber, so for us to make that possible with CM would be great.

Done! https://github.com/websharks/comment-mail/issues/114

**Comment by jaswsinc** [comment] 2015-06-26 16:01
I'm ignoring `stb_enabled` (Blog subscriptions) for now as a short-term solution, just to prevent CM from nagging when you only have blog subscriptions enabled.

**Comment by jaswsinc** [comment] 2015-06-26 16:02
My suggestion is that we close this now, and let that short-term solution suffice. Instead of putting more work into a KB article or a special notice about this, we can put our focus on #114 instead. If you agree, please feel free to close.

**Comment by raamdev** [comment] 2015-06-26 17:47
@jaswsinc Yep, that works for me. I noticed something in your commit (see https://github.com/websharks/comment-mail-pro/commit/110455bf9e523938d3f1dedee35142dccf42342f#commitcomment-11887387) that could be fixed. Also, can we update the Dashboard message then to specifically mention disabling "Jetpack Follow Comments in your WordPress Discussion Settings"? Right now the Dashboard message implies that you have to disable the entire Subscriptions module. 

Otherwise I agree, this issue can be closed.

**Comment by jaswsinc** [comment] 2015-06-26 18:12
@raamdev writes...
> I noticed something in your commit (see websharks/comment-mail-pro@110455b#commitcomment-11887387) that could be fixed

Thank you for catching that! :-)

@raamdev writes...
> Also, can we update the Dashboard message then to specifically mention disabling "Jetpack Follow Comments in your WordPress Discussion Settings"?

Done. Thanks :-)

![](https://www.filepicker.io/api/file/j7LsUilATXCFzlKfF8Ew#.png)

**Comment by raamdev** [comment] 2015-07-23 15:08
It appears the Dashboard message that warns when the Jetpack Subscriptions module is active with Follow Comments enabled is no longer working.

- WordPress v4.2.3
- Comment Mail Pro v150709
- Jetpack v3.6

![2015-07-23_11-06-22](https://cloud.githubusercontent.com/assets/53005/8853900/06b04e1c-312b-11e5-8406-ba844b776bbe.png)
![2015-07-23_11-07-04](https://cloud.githubusercontent.com/assets/53005/8853903/087411e8-312b-11e5-9030-1f1339e9aa75.png)

**Comment by jaswsinc** [comment] 2015-07-23 16:30
> WordPress v4.2.3
> Comment Mail Pro v150709
> Jetpack v3.6

Hmm. I wasn't able to reproduce this against 150709 or the latest dev branch. JetPack v3.6 and WordPress v4.3 alpha. I'll test against WordPress v4.2.3 though.

**Comment by raamdev** [comment] 2015-07-23 22:32
@jaswsinc Hmm, interesting. This was on a fresh install of WordPress too. 

For what it's worth, if I remember correctly, here's the order I did things:

1. Installed Comment Mail Pro, **did not activate**
1. Installed Jetpack and activated
1. Activated Comment Mail Pro

It was at that point that I realized I did not see any dashboard warning about Jetpack subscriptions. In fact, I haven't been able to get that Dashboard message to appear at all.

**Comment by jaswsinc** [comment] 2015-07-24 07:02
Weird. I still haven't been able to reproduce this.

If you get time to review this class member for any clues I'd appreciate it:
https://github.com/websharks/comment-mail-pro/blob/150709/comment-mail-pro/plugin.inc.php#L911

If nothing jumps out at you, can send me an export of your Comment Mail config. options privately?

**Comment by jaswsinc** [comment] 2015-07-24 17:26
I just got a JetPack update to v3.6.1 and I was also unable to reproduce it with the latest version.

**Comment by raamdev** [comment] 2015-07-24 20:28
> I just got a JetPack update to v3.6.1 and I was also unable to reproduce it with the latest version.

Ah, good, so it was related to the latest Jetpack update. Mystery solved!

**Comment by jaswsinc** [comment] 2015-07-24 22:52
No, I was _unable_ to reproduce it with JetPack v3.6.1 either.

**Comment by jaswsinc** [comment] 2015-07-24 22:55
Just for kicks, if that's a test site that you're experimenting with, you might try restarting the server and see if that makes any difference. Perhaps there is an opcode cache that contains the previous release of Comment Mail in memory still. That only comes to mind, because I had two issues earlier today that were related to that problem with PHP 5.5 running the Opcache extension with timestamp checking off.

http://php.net/manual/en/opcache.configuration.php#ini.opcache.validate-timestamps

**Comment by raamdev** [comment] 2015-07-24 22:55
> unable

Oh! Interesting. Let me run a few more tests and see if I can reproduce it.

> you might try restarting the server

Will do.

**Comment by raamdev** [comment] 2015-07-24 23:22
@jaswsinc I checked the server where I initially discovered this issue and that server does not have APC or Opcache installed.

I then used my `raam.websharks-inc.net` test site:

1. Disabled Comment Mail Plugin Deletion Safeguards 
1. Deactivated and deleted Comment Mail Pro
1. Updated Jetpack to 3.6.1 and confirmed "Follow Comments" was enabled in **Dashboard → Settings → Discussion**
1. Installed and activated Comment Mail Pro v150709
1. Enabled Comment Mail Pro

At that point I would've expected to see the warning about Jetpack + Comment Mail, but nothing. Only a message that said my settings were updated.

---

I'm not able to get that Jetpack + Comment Mail warning to show no matter what I do. 

Can you give me a list of steps you're following to get it to show?

**Comment by raamdev** [comment] 2015-07-24 23:34
Tested Comment Mail Lite v150709; same issue. No Dashboard message warning about potential Jetpack conflict.

**Comment by raamdev** [comment] 2015-07-24 23:37
Ah Ha! I I think I figured out the problem! 

When I go into **Dashboard → Settings → Discussion** and simply click "Save Changes" at the bottom, then the notice shows up!

![2015-07-24_19-35-37](https://cloud.githubusercontent.com/assets/53005/8886603/30b55bf6-323b-11e5-8d7b-b3447e8b84ec.png)

So, it sounds like the option that Comment Mail is checking for (maybe `stb_enabled` [on this line](https://github.com/websharks/comment-mail/commit/57ec109fb12418c304b5c6d04668d2e0d07b5619#diff-e4bab3f536e89477eaec08dbfca86222R1047) does't exist, until the Discussion Settings are actually saved, even though the Jetpack Follow Comments option _is_ enabled (it's enabled by default when you install Jetpack).

**Comment by jaswsinc** [comment] 2015-07-24 23:39
That's it! Nice work tracking that down.
Referencing: https://github.com/Automattic/jetpack/blob/202d1b80e9386aa6ed2dceb6ab9a4f362413e695/modules/comments/comments.php#L210

We need to pass a default option value in the second argument to `get_option()` in our check.

**Comment by jaswsinc** [comment] 2015-07-24 23:56
Next Lite Release:

- **JetPack Conflict Detection:** This release fixes a bug in the automatic JetPack conflict detection; i.e., if you enable JetPack Subscriptions w/ Follow Comments enabled together with Comment Mail at the same, a warning is displayed to notify you of a possible conflict in your configuration. See [this GitHub issue](https://github.com/websharks/comment-mail/issues/113) if you'd like to learn more.

**Comment by jaswsinc** [comment] 2015-07-24 23:56
Next Pro Release:

- **JetPack Conflict Detection:** This release fixes a bug in the automatic JetPack conflict detection; i.e., if you enable JetPack Subscriptions w/ Follow Comments enabled together with Comment Mail at the same, a warning is displayed to notify you of a possible conflict in your configuration. See [this GitHub issue](https://github.com/websharks/comment-mail/issues/113) if you'd like to learn more.

**Comment by raamdev** [comment] 2015-07-25 15:44
@jaswsinc Thanks for fixing that! :-)

One other thing I just noticed about that Dashboard notice is that it doesn't say _where_ you can update those Jetpack settings. I suggest we add the following to that message:

![2015-07-25_11-43-03](https://cloud.githubusercontent.com/assets/53005/8890106/6f75c0ba-32c2-11e5-8500-b28e390e8d04.png)

I'll submit a PR for this now.

**Comment by jaswsinc** [comment] 2015-07-27 09:39
@raamdev Merged. Thanks! :-)

**Closed by jaswsinc** 2015-07-27 09:39 UTC
Labels: partial completion, todo

**Comment by raamdev** [comment] 2015-12-24 23:14
**Comment Mail v151224** has been released and includes changes from this GitHub Issue: See the [v151224 announcement](http://comment-mail.com/comment-mail-v151224-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#113).
